project_id = "ctcekfsvvmwcirogpipk"

[functions.scrape-product]
verify_jwt = false

[functions.scrape-category]
verify_jwt = false

[functions.generate-product-content]
verify_jwt = false

[functions.send-invoice]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.download-vehicle-images]
verify_jwt = false

[functions.estimate-vehicle-price]
verify_jwt = false

[functions.assign-vehicle-categories]
verify_jwt = false

[functions.translate-vehicles]
verify_jwt = false
